<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bazaar"
 *
 * Auto generated by Extension Builder 2017-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bazaar',
	'description' => 'TYPO3 Online Shop',
	'category' => 'plugin',
	'author' => 'Christopher Zechendorf',
	'author_email' => 'christopher@zechendorf.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
